// Generated by scripts/build-bugs.mts; do not edit.
window.BUG_CATALOG = {
 "title": "Bugs",
 "prefix": "BUG",
 "generatedAt": "2026-10-09T19:25:38.124Z",
 "commit": "b15b7923f10f60c57e5a73beb6baeb21d6b06604",
 "repoUrl": "https://github.com/Zaytsman/SimpRight",
 "branch": "main",
 "bugsDir": "bugs",
 "layers": {
  "ui": "UI",
  "api": "API"
 },
 "regressions": [
  {
   "layer": "ui",
   "label": "daily UI regression",
   "results": "../latest/daily-ui-regression/results.json",
   "report": "../latest/daily-ui-regression/"
  },
  {
   "layer": "api",
   "label": "daily API regression",
   "results": "../latest/daily-api-regression/results.json",
   "report": "../latest/daily-api-regression/"
  }
 ],
 "stats": {
  "total": 8,
  "open": 8,
  "fixed": 0,
  "wontFix": 0
 },
 "bugs": [
  {
   "id": "BUG-001",
   "title": "Product writes (POST, PUT, PATCH /products) succeed without a token instead of returning 401",
   "status": "open",
   "severity": "critical",
   "layer": "api",
   "area": "products",
   "affects": [
    "POST /products",
    "PUT /products/{productId}",
    "PATCH /products/{productId}"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#notes"
   ],
   "description": "Anyone can create or change products without logging in: ProductController has no auth middleware on these routes (only DELETE is admin-only), and the OpenAPI spec declares no security on them either. Visitors of the demo site change seeded products this way (stock, price, category).",
   "steps": [
    "Send GET /products and take the first item's brand id, category id and product image id.",
    "Send POST /products with a unique product name, a positive price and those ids, without an Authorization header.",
    "Send PUT or PATCH /products/{productId} for the new product with a new name, without an Authorization header."
   ],
   "expected": "Each write without a token returns 401 and changes nothing.",
   "actual": "POST returns 201 and creates the product; PUT and PATCH return 200 and change it.",
   "file": "bugs/BUG-001.yml",
   "yaml": "id: BUG-001\ntitle: Product writes (POST, PUT, PATCH /products) succeed without a token instead of returning 401\nstatus: open\nseverity: critical\nlayer: api\narea: products\naffects:\n  - POST /products\n  - PUT /products/{productId}\n  - PATCH /products/{productId}\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#notes\ndescription: >-\n  Anyone can create or change products without logging in: ProductController has no auth middleware\n  on these routes (only DELETE is admin-only), and the OpenAPI spec declares no security on them either.\n  Visitors of the demo site change seeded products this way (stock, price, category).\nsteps:\n  - Send GET /products and take the first item's brand id, category id and product image id.\n  - Send POST /products with a unique product name, a positive price and those ids, without an Authorization header.\n  - Send PUT or PATCH /products/{productId} for the new product with a new name, without an Authorization header.\nexpected: Each write without a token returns 401 and changes nothing.\nactual: POST returns 201 and creates the product; PUT and PATCH return 200 and change it.",
   "scenarios": [
    {
     "id": "API-0057",
     "name": "Partially update product without a token returns 401",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/patch-products-by-product-id.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/patch-products-by-product-id.spec.ts",
     "specLine": 153,
     "knownIssue": "Accepts PATCH without a token instead of returning 401."
    },
    {
     "id": "API-0042",
     "name": "Create product without a token returns 401",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/post-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/post-products.spec.ts",
     "specLine": 352,
     "knownIssue": "Accepts POST without a token instead of returning 401."
    },
    {
     "id": "API-0051",
     "name": "Update product without a token returns 401",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/put-products-by-product-id.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/put-products-by-product-id.spec.ts",
     "specLine": 237,
     "knownIssue": "Accepts PUT without a token instead of returning 401."
    }
   ]
  },
  {
   "id": "BUG-002",
   "title": "Create product returns 500 instead of 422 when category_id, brand_id or product_image_id doesn't exist",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "products",
   "affects": [
    "POST /products"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#3-create-product"
   ],
   "description": "The request validation doesn't check that the referenced category, brand and product image exist, so the database's foreign-key error surfaces as a server error instead of a validation message.",
   "steps": [
    "Send GET /products and take the first item's brand id, category id and product image id.",
    "Send POST /products with a unique product name, a positive price and those ids, but with one of category_id, brand_id or product_image_id set to an id that doesn't exist."
   ],
   "expected": "422 with a validation message for the unknown id.",
   "actual": "500 for each of the three fields (read from the source; the scenarios' checks of 422 fail live).",
   "file": "bugs/BUG-002.yml",
   "yaml": "id: BUG-002\ntitle: Create product returns 500 instead of 422 when category_id, brand_id or product_image_id doesn't exist\nstatus: open\nseverity: major\nlayer: api\narea: products\naffects:\n  - POST /products\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#3-create-product\ndescription: >-\n  The request validation doesn't check that the referenced category, brand and product image exist,\n  so the database's foreign-key error surfaces as a server error instead of a validation message.\nsteps:\n  - Send GET /products and take the first item's brand id, category id and product image id.\n  - Send POST /products with a unique product name, a positive price and those ids, but with one of category_id, brand_id or product_image_id set to an id that doesn't exist.\nexpected: 422 with a validation message for the unknown id.\nactual: 500 for each of the three fields (read from the source; the scenarios' checks of 422 fail live).",
   "scenarios": [
    {
     "id": "API-0039",
     "name": "Create product with an unknown category id returns 422",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/post-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/post-products.spec.ts",
     "specLine": 256,
     "knownIssue": "Returns 500 instead of 422 when category_id doesn't exist."
    },
    {
     "id": "API-0040",
     "name": "Create product with an unknown brand id returns 422",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/post-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/post-products.spec.ts",
     "specLine": 288,
     "knownIssue": "Returns 500 instead of 422 when brand_id doesn't exist."
    },
    {
     "id": "API-0041",
     "name": "Create product with an unknown product image id returns 422",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/post-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/post-products.spec.ts",
     "specLine": 320,
     "knownIssue": "Returns 500 instead of 422 when product_image_id doesn't exist."
    }
   ]
  },
  {
   "id": "BUG-003",
   "title": "Product list returns 500 for an unknown sort column instead of a client error",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "products",
   "affects": [
    "GET /products",
    "QUERY /products"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#1-list-products",
    "docs/api/contracts/Products_API.md#2-list-products-http-query"
   ],
   "description": "The sort column goes to the database query without a check against the allowed columns. GET and QUERY share the code path, so both fail the same way.",
   "steps": [
    "Send GET /products with sort=no_such_column,asc.",
    "Send QUERY /products with Content-Type: application/json and the body { \"sort\": \"no_such_column,asc\" }."
   ],
   "expected": "400 or 422 naming the sort column, or 200 with the column ignored.",
   "actual": "500 for both.",
   "evidence": "GET /products?sort=no_such_column,asc (Accept: application/json), 2026-10-09\n-> 500 {\"message\":\"Something went wrong\"}",
   "file": "bugs/BUG-003.yml",
   "yaml": "id: BUG-003\ntitle: Product list returns 500 for an unknown sort column instead of a client error\nstatus: open\nseverity: major\nlayer: api\narea: products\naffects:\n  - GET /products\n  - QUERY /products\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#1-list-products\n  - docs/api/contracts/Products_API.md#2-list-products-http-query\ndescription: >-\n  The sort column goes to the database query without a check against the allowed columns.\n  GET and QUERY share the code path, so both fail the same way.\nsteps:\n  - Send GET /products with sort=no_such_column,asc.\n  - 'Send QUERY /products with Content-Type: application/json and the body { \"sort\": \"no_such_column,asc\" }.'\nexpected: 400 or 422 naming the sort column, or 200 with the column ignored.\nactual: 500 for both.\nevidence: |-\n  GET /products?sort=no_such_column,asc (Accept: application/json), 2026-10-09\n  -> 500 {\"message\":\"Something went wrong\"}",
   "scenarios": [
    {
     "id": "API-0014",
     "name": "Unknown sort column is not a server error",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/get-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/get-products.spec.ts",
     "specLine": 410,
     "knownIssue": "Returns 500 instead of a client error (or ignoring the column) for an unknown sort column."
    },
    {
     "id": "API-0019",
     "name": "QUERY list with an unknown sort column is not a server error",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/query-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/query-products.spec.ts",
     "specLine": 210,
     "knownIssue": "Returns 500 instead of a client error (or ignoring the column) for an unknown sort column."
    }
   ]
  },
  {
   "id": "BUG-004",
   "title": "Related products for an unknown product id return 500 instead of 404",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "products",
   "affects": [
    "GET /products/{productId}/related"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#8-get-related-products"
   ],
   "steps": [
    "Send GET /products/{productId}/related with a well-formed ULID that no product has."
   ],
   "expected": "404, like GET /products/{productId} for the same id.",
   "actual": "500 with { \"message\": \"Server Error\" }.",
   "evidence": "GET /products/01AAAAAAAAAAAAAAAAAAAAAAAA/related (Accept: application/json), 2026-10-09\n-> 500 {\"message\":\"Server Error\"}",
   "file": "bugs/BUG-004.yml",
   "yaml": "id: BUG-004\ntitle: Related products for an unknown product id return 500 instead of 404\nstatus: open\nseverity: major\nlayer: api\narea: products\naffects:\n  - GET /products/{productId}/related\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#8-get-related-products\nsteps:\n  - Send GET /products/{productId}/related with a well-formed ULID that no product has.\nexpected: 404, like GET /products/{productId} for the same id.\nactual: '500 with { \"message\": \"Server Error\" }.'\nevidence: |-\n  GET /products/01AAAAAAAAAAAAAAAAAAAAAAAA/related (Accept: application/json), 2026-10-09\n  -> 500 {\"message\":\"Server Error\"}",
   "scenarios": [
    {
     "id": "API-0024",
     "name": "Related products for an unknown product id return 404",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/get-products-by-product-id-related.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/get-products-by-product-id-related.spec.ts",
     "specLine": 70,
     "knownIssue": "Returns 500 instead of 404 for an unknown product id."
    }
   ]
  },
  {
   "id": "BUG-006",
   "title": "Token refresh returns 500 instead of 401 without a token or with a malformed one",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "users",
   "affects": [
    "GET /users/refresh"
   ],
   "found": "2026-10-03",
   "ref": [
    "docs/api/contracts/Users_API.md#7-refresh-token"
   ],
   "description": "An expired or invalidated token gets a proper 401; only a missing or unparsable one ends in a server error.",
   "steps": [
    "Send GET /users/refresh without an Authorization header.",
    "Send GET /users/refresh with Authorization \"Bearer not-a-jwt\"."
   ],
   "expected": "401 for both.",
   "actual": "500 with { \"message\": \"Server Error\" } for both.",
   "evidence": "GET /users/refresh (no Authorization), 2026-10-09 -> 500 {\"message\":\"Server Error\"}\nGET /users/refresh (Authorization: Bearer not-a-jwt), 2026-10-09 -> 500 {\"message\":\"Server Error\"}",
   "file": "bugs/BUG-006.yml",
   "yaml": "id: BUG-006\ntitle: Token refresh returns 500 instead of 401 without a token or with a malformed one\nstatus: open\nseverity: major\nlayer: api\narea: users\naffects:\n  - GET /users/refresh\nfound: 2026-10-03\nref:\n  - docs/api/contracts/Users_API.md#7-refresh-token\ndescription: >-\n  An expired or invalidated token gets a proper 401; only a missing or unparsable one ends in a server error.\nsteps:\n  - Send GET /users/refresh without an Authorization header.\n  - Send GET /users/refresh with Authorization \"Bearer not-a-jwt\".\nexpected: 401 for both.\nactual: '500 with { \"message\": \"Server Error\" } for both.'\nevidence: |-\n  GET /users/refresh (no Authorization), 2026-10-09 -> 500 {\"message\":\"Server Error\"}\n  GET /users/refresh (Authorization: Bearer not-a-jwt), 2026-10-09 -> 500 {\"message\":\"Server Error\"}",
   "scenarios": [
    {
     "id": "API-0112",
     "name": "Refresh without a token returns 401",
     "layer": "api",
     "area": "users",
     "file": "test-scenarios/api/users/get-users-refresh.yml",
     "status": "automated",
     "automatedIn": "tests/api/users/get-users-refresh.spec.ts",
     "specLine": 128,
     "knownIssue": "Returns 500 instead of 401 when the request has no token."
    },
    {
     "id": "API-0113",
     "name": "Refresh with a malformed token returns 401",
     "layer": "api",
     "area": "users",
     "file": "test-scenarios/api/users/get-users-refresh.yml",
     "status": "automated",
     "automatedIn": "tests/api/users/get-users-refresh.spec.ts",
     "specLine": 142,
     "knownIssue": "Returns 500 instead of 401 for a malformed token."
    }
   ]
  },
  {
   "id": "BUG-007",
   "title": "Registration accepts customers older than 75; the age limit only rejects birth dates more than 93 years ago",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "users",
   "affects": [
    "POST /users/register"
   ],
   "found": "2026-10-03",
   "ref": [
    "docs/api/contracts/Users_API.md#notes"
   ],
   "description": "The rule behind \"Customer must be younger than 75 years old.\" subtracts 75 years from a date that already had 18 subtracted (the minimum-age check), so the upper limit is 93 years, not 75.",
   "steps": [
    "Send POST /users/register with a unique email, a first name, a last name, a random strong password and a dob 80 years ago in YYYY-MM-DD."
   ],
   "expected": "422 with the dob message \"Customer must be younger than 75 years old.\".",
   "actual": "201; the customer is registered.",
   "file": "bugs/BUG-007.yml",
   "yaml": "id: BUG-007\ntitle: Registration accepts customers older than 75; the age limit only rejects birth dates more than 93 years ago\nstatus: open\nseverity: major\nlayer: api\narea: users\naffects:\n  - POST /users/register\nfound: 2026-10-03\nref:\n  - docs/api/contracts/Users_API.md#notes\ndescription: >-\n  The rule behind \"Customer must be younger than 75 years old.\" subtracts 75 years from a date that\n  already had 18 subtracted (the minimum-age check), so the upper limit is 93 years, not 75.\nsteps:\n  - Send POST /users/register with a unique email, a first name, a last name, a random strong password and a dob 80 years ago in YYYY-MM-DD.\nexpected: 422 with the dob message \"Customer must be younger than 75 years old.\".\nactual: 201; the customer is registered.",
   "scenarios": [
    {
     "id": "API-0099",
     "name": "Register a customer older than 75 returns 422",
     "layer": "api",
     "area": "users",
     "file": "test-scenarios/api/users/post-users-register.yml",
     "status": "automated",
     "automatedIn": "tests/api/users/post-users-register.spec.ts",
     "specLine": 421,
     "knownIssue": "Accepts a customer born 80 years ago (201) instead of 422; the 75-year age limit only rejects birth dates more than 93 years ago."
    }
   ]
  },
  {
   "id": "BUG-008",
   "title": "Cart quantity stops at 99 instead of the story's range of 1 to 999,999,999",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "carts",
   "affects": [
    "POST /carts/{cartId}",
    "/product/{productId}"
   ],
   "found": "2026-10-04",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC7",
    "docs/analysis/product-detail.md",
    "docs/api/contracts/Carts_API.md#2-add-item-to-cart"
   ],
   "description": "The story requires quantities from 1 to 999,999,999, but the app caps them at 99 in three places: the server's validation (max:99 in CartController::addItem), the browser's cart service and the product page's quantity field (MAX_QUANTITY = 99).",
   "steps": [
    "Send POST /carts with an empty body and take the returned id.",
    "Send POST /carts/{cartId} with that id, an existing product's id as product_id and quantity 999999999."
   ],
   "expected": "200, and GET /carts/{cartId} shows the item with quantity 999999999.",
   "actual": "422 with a quantity error; the server accepts at most 99.",
   "evidence": "Page inspector, /product/01M4H0KC65RV1AZDGBVVX7XJ9G (Combination Pliers, logged out), 2026-10-09\n-> data-test \"quantity\": input[number], limits: min 1, max 99\nSource (practice-software-testing, sprint5), 2026-10-09:\nUI detail.component.ts validateQuantity(): a typed value above MAX_QUANTITY (99) becomes 99,\n  with the toast \"You can order at most 99 of this product.\"\nUI cart.service.ts addItem()/replaceQuantity(): Math.min(Math.max(1, quantity), 99)\nAPI CartController addItem/updateQuantity: 'quantity' => 'required|integer|min:1|max:99'",
   "file": "bugs/BUG-008.yml",
   "yaml": "id: BUG-008\ntitle: Cart quantity stops at 99 instead of the story's range of 1 to 999,999,999\nstatus: open\nseverity: major\nlayer: api\narea: carts\naffects:\n  - POST /carts/{cartId}\n  - /product/{productId}\nfound: 2026-10-04\nref:\n  - docs/ui/user-stories/Product_Detail.md#AC7\n  - docs/analysis/product-detail.md\n  - docs/api/contracts/Carts_API.md#2-add-item-to-cart\ndescription: >-\n  The story requires quantities from 1 to 999,999,999, but the app caps them at 99 in three places:\n  the server's validation (max:99 in CartController::addItem), the browser's cart service and the\n  product page's quantity field (MAX_QUANTITY = 99).\nsteps:\n  - Send POST /carts with an empty body and take the returned id.\n  - Send POST /carts/{cartId} with that id, an existing product's id as product_id and quantity 999999999.\nexpected: 200, and GET /carts/{cartId} shows the item with quantity 999999999.\nactual: 422 with a quantity error; the server accepts at most 99.\nevidence: |-\n  Page inspector, /product/01M4H0KC65RV1AZDGBVVX7XJ9G (Combination Pliers, logged out), 2026-10-09\n  -> data-test \"quantity\": input[number], limits: min 1, max 99\n  Source (practice-software-testing, sprint5), 2026-10-09:\n  UI detail.component.ts validateQuantity(): a typed value above MAX_QUANTITY (99) becomes 99,\n    with the toast \"You can order at most 99 of this product.\"\n  UI cart.service.ts addItem()/replaceQuantity(): Math.min(Math.max(1, quantity), 99)\n  API CartController addItem/updateQuantity: 'quantity' => 'required|integer|min:1|max:99'",
   "scenarios": [
    {
     "id": "API-0118",
     "name": "Add a product with quantity 999,999,999 to a cart returns 200 and the cart holds it",
     "layer": "api",
     "area": "carts",
     "file": "test-scenarios/api/carts/post-carts-by-cart-id.yml",
     "status": "automated",
     "automatedIn": "tests/api/carts/post-carts-by-cart-id.spec.ts",
     "specLine": 235,
     "knownIssue": "Returns 422 for a quantity of 999,999,999 (the server allows at most 99) instead of adding it to the cart as the story's range 1 to 999,999,999 requires."
    },
    {
     "id": "UI-024",
     "name": "A typed quantity above 999,999,999 is set to 999,999,999",
     "layer": "ui",
     "area": "products",
     "file": "test-scenarios/ui/products/product-quantity.yml",
     "status": "manual",
     "knownIssue": "The field sets a typed quantity above 99 to 99 (with the warning \"You can order at most 99 of this product.\") instead of setting 1,000,000,000 to 999,999,999 as the story's range 1 to 999,999,999 requires."
    },
    {
     "id": "UI-025",
     "name": "A typed quantity of 999,999,999 is accepted",
     "layer": "ui",
     "area": "products",
     "file": "test-scenarios/ui/products/product-quantity.yml",
     "status": "manual",
     "knownIssue": "The field changes a typed quantity of 999,999,999 to 99 (the app allows at most 99) instead of keeping it as the story's range 1 to 999,999,999 requires."
    }
   ]
  },
  {
   "id": "BUG-005",
   "title": "Related products omit co2_rating, so is_eco_friendly is always false",
   "status": "open",
   "severity": "minor",
   "layer": "api",
   "area": "products",
   "affects": [
    "GET /products/{productId}/related"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#notes"
   ],
   "description": "The related-products query doesn't select co2_rating, so the field is missing and is_eco_friendly, which is derived from it, is false for every related product. The same products from GET /products/{productId} have it.",
   "steps": [
    "Send GET /products and take the first item's id.",
    "Send GET /products/{productId}/related with that id.",
    "Compare the items with GET /products/{productId} for each of them."
   ],
   "expected": "Every related product has co2_rating, and is_eco_friendly matches it.",
   "actual": "No related product has co2_rating, and is_eco_friendly is false for all of them.",
   "evidence": "GET /products/01M4GX5NBG86XPB5G15W625EMS/related, 2026-10-09\n-> 200, 4 items with keys id, name, description, price, is_location_offer, is_rental, in_stock,\n   is_eco_friendly (false), product_image, category, brand; no co2_rating\nGET /products/01M4GX5NBG86XPB5G15W625EMS -> co2_rating \"D\"",
   "file": "bugs/BUG-005.yml",
   "yaml": "id: BUG-005\ntitle: Related products omit co2_rating, so is_eco_friendly is always false\nstatus: open\nseverity: minor\nlayer: api\narea: products\naffects:\n  - GET /products/{productId}/related\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#notes\ndescription: >-\n  The related-products query doesn't select co2_rating, so the field is missing and is_eco_friendly,\n  which is derived from it, is false for every related product. The same products from GET /products/{productId} have it.\nsteps:\n  - Send GET /products and take the first item's id.\n  - Send GET /products/{productId}/related with that id.\n  - Compare the items with GET /products/{productId} for each of them.\nexpected: Every related product has co2_rating, and is_eco_friendly matches it.\nactual: No related product has co2_rating, and is_eco_friendly is false for all of them.\nevidence: |-\n  GET /products/01M4GX5NBG86XPB5G15W625EMS/related, 2026-10-09\n  -> 200, 4 items with keys id, name, description, price, is_location_offer, is_rental, in_stock,\n     is_eco_friendly (false), product_image, category, brand; no co2_rating\n  GET /products/01M4GX5NBG86XPB5G15W625EMS -> co2_rating \"D\"",
   "scenarios": [
    {
     "id": "API-0025",
     "name": "Related products include their CO2 rating",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/get-products-by-product-id-related.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/get-products-by-product-id-related.spec.ts",
     "specLine": 87,
     "knownIssue": "Omits co2_rating from related products, so is_eco_friendly is always false."
    }
   ]
  }
 ]
};
