// Generated by scripts/build-bugs.mts; do not edit.
window.BUG_CATALOG = {
 "title": "Bugs",
 "prefix": "BUG",
 "generatedAt": "2026-10-10T08:20:23.949Z",
 "commit": "0ef9b23b0a0746bd9bdad3adf7292666bb9acab4",
 "repoUrl": "https://github.com/Zaytsman/SimpRight",
 "branch": "main",
 "bugsDir": "bugs",
 "layers": {
  "ui": "UI",
  "api": "API"
 },
 "regressions": [
  {
   "layer": "ui",
   "label": "daily UI regression",
   "results": "../latest/daily-ui-regression/results.json",
   "report": "../latest/daily-ui-regression/"
  },
  {
   "layer": "api",
   "label": "daily API regression",
   "results": "../latest/daily-api-regression/results.json",
   "report": "../latest/daily-api-regression/"
  }
 ],
 "stats": {
  "total": 13,
  "open": 13,
  "fixed": 0,
  "wontFix": 0
 },
 "bugs": [
  {
   "id": "BUG-001",
   "title": "Product writes (POST, PUT, PATCH /products) succeed without a token instead of returning 401",
   "status": "open",
   "severity": "critical",
   "layer": "api",
   "area": "products",
   "affects": [
    "POST /products",
    "PUT /products/{productId}",
    "PATCH /products/{productId}"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#notes"
   ],
   "description": "Anyone can create or change products without logging in: ProductController has no auth middleware on these routes (only DELETE is admin-only), and the OpenAPI spec declares no security on them either. Visitors of the demo site change seeded products this way (stock, price, category).",
   "steps": [
    "Send GET /products and take the first item's brand id, category id and product image id.",
    "Send POST /products with a unique product name, a positive price and those ids, without an Authorization header.",
    "Send PUT or PATCH /products/{productId} for the new product with a new name, without an Authorization header."
   ],
   "expected": "Each write without a token returns 401 and changes nothing.",
   "actual": "POST returns 201 and creates the product; PUT and PATCH return 200 and change it.",
   "file": "bugs/BUG-001.yml",
   "yaml": "id: BUG-001\ntitle: Product writes (POST, PUT, PATCH /products) succeed without a token instead of returning 401\nstatus: open\nseverity: critical\nlayer: api\narea: products\naffects:\n  - POST /products\n  - PUT /products/{productId}\n  - PATCH /products/{productId}\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#notes\ndescription: >-\n  Anyone can create or change products without logging in: ProductController has no auth middleware\n  on these routes (only DELETE is admin-only), and the OpenAPI spec declares no security on them either.\n  Visitors of the demo site change seeded products this way (stock, price, category).\nsteps:\n  - Send GET /products and take the first item's brand id, category id and product image id.\n  - Send POST /products with a unique product name, a positive price and those ids, without an Authorization header.\n  - Send PUT or PATCH /products/{productId} for the new product with a new name, without an Authorization header.\nexpected: Each write without a token returns 401 and changes nothing.\nactual: POST returns 201 and creates the product; PUT and PATCH return 200 and change it.",
   "scenarios": [
    {
     "id": "API-0057",
     "name": "Partially update product without a token returns 401",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/patch-products-by-product-id.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/patch-products-by-product-id.spec.ts",
     "specLine": 153,
     "knownIssue": "Accepts PATCH without a token instead of returning 401."
    },
    {
     "id": "API-0042",
     "name": "Create product without a token returns 401",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/post-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/post-products.spec.ts",
     "specLine": 352,
     "knownIssue": "Accepts POST without a token instead of returning 401."
    },
    {
     "id": "API-0051",
     "name": "Update product without a token returns 401",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/put-products-by-product-id.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/put-products-by-product-id.spec.ts",
     "specLine": 237,
     "knownIssue": "Accepts PUT without a token instead of returning 401."
    }
   ]
  },
  {
   "id": "BUG-009",
   "title": "Brand writes (POST, PUT, PATCH /brands) succeed without a token instead of returning 401",
   "status": "open",
   "severity": "critical",
   "layer": "api",
   "area": "brands",
   "affects": [
    "POST /brands",
    "PUT /brands/{brandId}",
    "PATCH /brands/{brandId}"
   ],
   "found": "2026-10-10",
   "ref": [
    "docs/api/contracts/Brands_API.md#authentication",
    "docs/api/contracts/Brands_API.md#notes"
   ],
   "description": "Anyone can create brands or rename seeded ones without logging in: BrandController has no auth middleware on these routes (only DELETE is admin-only), and the OpenAPI spec declares no security on them either. The same pattern as BUG-001 (products), in a separate controller.",
   "steps": [
    "Send POST /brands with a unique name and a unique slug, without an Authorization header, and take the new brand's id.",
    "Send PUT /brands/{brandId} for the new brand with a new name, without an Authorization header.",
    "Send PATCH /brands/{brandId} for the new brand with a new name, without an Authorization header."
   ],
   "expected": "Each write without a token returns 401 and changes nothing, like DELETE /brands/{brandId} without a token.",
   "actual": "POST returns 201 and creates the brand; PUT and PATCH return 200 and change it.",
   "evidence": "Throwaway brand, no Authorization header, 2026-10-10 08:07 UTC (deleted as admin afterwards, 204)\nPOST /brands { name, slug: unique } -> 201 { name, slug, id }\nPUT /brands/{brandId} { name: new } -> 200 {\"success\":true}\nPATCH /brands/{brandId} { name: new } -> 200 {\"success\":true}\nGET /brands/{brandId} -> 200, the name from the PATCH\nSource (practice-software-testing, sprint5/API): BrandController::__construct:\n  $this->middleware('role:admin', ['only' => ['destroy']]); no other auth middleware",
   "file": "bugs/BUG-009.yml",
   "yaml": "id: BUG-009\ntitle: Brand writes (POST, PUT, PATCH /brands) succeed without a token instead of returning 401\nstatus: open\nseverity: critical\nlayer: api\narea: brands\naffects:\n  - POST /brands\n  - PUT /brands/{brandId}\n  - PATCH /brands/{brandId}\nfound: 2026-10-10\nref:\n  - docs/api/contracts/Brands_API.md#authentication\n  - docs/api/contracts/Brands_API.md#notes\ndescription: >-\n  Anyone can create brands or rename seeded ones without logging in: BrandController has no auth\n  middleware on these routes (only DELETE is admin-only), and the OpenAPI spec declares no security on\n  them either. The same pattern as BUG-001 (products), in a separate controller.\nsteps:\n  - Send POST /brands with a unique name and a unique slug, without an Authorization header, and take the new brand's id.\n  - Send PUT /brands/{brandId} for the new brand with a new name, without an Authorization header.\n  - Send PATCH /brands/{brandId} for the new brand with a new name, without an Authorization header.\nexpected: Each write without a token returns 401 and changes nothing, like DELETE /brands/{brandId} without a token.\nactual: POST returns 201 and creates the brand; PUT and PATCH return 200 and change it.\nevidence: |-\n  Throwaway brand, no Authorization header, 2026-10-10 08:07 UTC (deleted as admin afterwards, 204)\n  POST /brands { name, slug: unique } -> 201 { name, slug, id }\n  PUT /brands/{brandId} { name: new } -> 200 {\"success\":true}\n  PATCH /brands/{brandId} { name: new } -> 200 {\"success\":true}\n  GET /brands/{brandId} -> 200, the name from the PATCH\n  Source (practice-software-testing, sprint5/API): BrandController::__construct:\n    $this->middleware('role:admin', ['only' => ['destroy']]); no other auth middleware",
   "scenarios": []
  },
  {
   "id": "BUG-002",
   "title": "Create product returns 500 instead of 422 when category_id, brand_id or product_image_id doesn't exist",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "products",
   "affects": [
    "POST /products"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#3-create-product"
   ],
   "description": "The request validation doesn't check that the referenced category, brand and product image exist, so the database's foreign-key error surfaces as a server error instead of a validation message.",
   "steps": [
    "Send GET /products and take the first item's brand id, category id and product image id.",
    "Send POST /products with a unique product name, a positive price and those ids, but with one of category_id, brand_id or product_image_id set to an id that doesn't exist."
   ],
   "expected": "422 with a validation message for the unknown id.",
   "actual": "500 for each of the three fields (read from the source; the scenarios' checks of 422 fail live).",
   "file": "bugs/BUG-002.yml",
   "yaml": "id: BUG-002\ntitle: Create product returns 500 instead of 422 when category_id, brand_id or product_image_id doesn't exist\nstatus: open\nseverity: major\nlayer: api\narea: products\naffects:\n  - POST /products\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#3-create-product\ndescription: >-\n  The request validation doesn't check that the referenced category, brand and product image exist,\n  so the database's foreign-key error surfaces as a server error instead of a validation message.\nsteps:\n  - Send GET /products and take the first item's brand id, category id and product image id.\n  - Send POST /products with a unique product name, a positive price and those ids, but with one of category_id, brand_id or product_image_id set to an id that doesn't exist.\nexpected: 422 with a validation message for the unknown id.\nactual: 500 for each of the three fields (read from the source; the scenarios' checks of 422 fail live).",
   "scenarios": [
    {
     "id": "API-0039",
     "name": "Create product with an unknown category id returns 422",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/post-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/post-products.spec.ts",
     "specLine": 256,
     "knownIssue": "Returns 500 instead of 422 when category_id doesn't exist."
    },
    {
     "id": "API-0040",
     "name": "Create product with an unknown brand id returns 422",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/post-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/post-products.spec.ts",
     "specLine": 288,
     "knownIssue": "Returns 500 instead of 422 when brand_id doesn't exist."
    },
    {
     "id": "API-0041",
     "name": "Create product with an unknown product image id returns 422",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/post-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/post-products.spec.ts",
     "specLine": 320,
     "knownIssue": "Returns 500 instead of 422 when product_image_id doesn't exist."
    }
   ]
  },
  {
   "id": "BUG-003",
   "title": "Product list returns 500 for an unknown sort column instead of a client error",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "products",
   "affects": [
    "GET /products",
    "QUERY /products"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#1-list-products",
    "docs/api/contracts/Products_API.md#2-list-products-http-query"
   ],
   "description": "The sort column goes to the database query without a check against the allowed columns. GET and QUERY share the code path, so both fail the same way.",
   "steps": [
    "Send GET /products with sort=no_such_column,asc.",
    "Send QUERY /products with Content-Type: application/json and the body { \"sort\": \"no_such_column,asc\" }."
   ],
   "expected": "400 or 422 naming the sort column, or 200 with the column ignored.",
   "actual": "500 for both.",
   "evidence": "GET /products?sort=no_such_column,asc (Accept: application/json), 2026-10-09\n-> 500 {\"message\":\"Something went wrong\"}",
   "file": "bugs/BUG-003.yml",
   "yaml": "id: BUG-003\ntitle: Product list returns 500 for an unknown sort column instead of a client error\nstatus: open\nseverity: major\nlayer: api\narea: products\naffects:\n  - GET /products\n  - QUERY /products\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#1-list-products\n  - docs/api/contracts/Products_API.md#2-list-products-http-query\ndescription: >-\n  The sort column goes to the database query without a check against the allowed columns.\n  GET and QUERY share the code path, so both fail the same way.\nsteps:\n  - Send GET /products with sort=no_such_column,asc.\n  - 'Send QUERY /products with Content-Type: application/json and the body { \"sort\": \"no_such_column,asc\" }.'\nexpected: 400 or 422 naming the sort column, or 200 with the column ignored.\nactual: 500 for both.\nevidence: |-\n  GET /products?sort=no_such_column,asc (Accept: application/json), 2026-10-09\n  -> 500 {\"message\":\"Something went wrong\"}",
   "scenarios": [
    {
     "id": "API-0014",
     "name": "Unknown sort column is not a server error",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/get-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/get-products.spec.ts",
     "specLine": 410,
     "knownIssue": "Returns 500 instead of a client error (or ignoring the column) for an unknown sort column."
    },
    {
     "id": "API-0019",
     "name": "QUERY list with an unknown sort column is not a server error",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/query-products.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/query-products.spec.ts",
     "specLine": 210,
     "knownIssue": "Returns 500 instead of a client error (or ignoring the column) for an unknown sort column."
    }
   ]
  },
  {
   "id": "BUG-004",
   "title": "Related products for an unknown product id return 500 instead of 404",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "products",
   "affects": [
    "GET /products/{productId}/related"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#8-get-related-products"
   ],
   "steps": [
    "Send GET /products/{productId}/related with a well-formed ULID that no product has."
   ],
   "expected": "404, like GET /products/{productId} for the same id.",
   "actual": "500 with { \"message\": \"Server Error\" }.",
   "evidence": "GET /products/01AAAAAAAAAAAAAAAAAAAAAAAA/related (Accept: application/json), 2026-10-09\n-> 500 {\"message\":\"Server Error\"}",
   "file": "bugs/BUG-004.yml",
   "yaml": "id: BUG-004\ntitle: Related products for an unknown product id return 500 instead of 404\nstatus: open\nseverity: major\nlayer: api\narea: products\naffects:\n  - GET /products/{productId}/related\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#8-get-related-products\nsteps:\n  - Send GET /products/{productId}/related with a well-formed ULID that no product has.\nexpected: 404, like GET /products/{productId} for the same id.\nactual: '500 with { \"message\": \"Server Error\" }.'\nevidence: |-\n  GET /products/01AAAAAAAAAAAAAAAAAAAAAAAA/related (Accept: application/json), 2026-10-09\n  -> 500 {\"message\":\"Server Error\"}",
   "scenarios": [
    {
     "id": "API-0024",
     "name": "Related products for an unknown product id return 404",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/get-products-by-product-id-related.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/get-products-by-product-id-related.spec.ts",
     "specLine": 70,
     "knownIssue": "Returns 500 instead of 404 for an unknown product id."
    }
   ]
  },
  {
   "id": "BUG-006",
   "title": "Token refresh returns 500 instead of 401 without a token or with a malformed one",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "users",
   "affects": [
    "GET /users/refresh"
   ],
   "found": "2026-10-03",
   "ref": [
    "docs/api/contracts/Users_API.md#7-refresh-token"
   ],
   "description": "An expired or invalidated token gets a proper 401; only a missing or unparsable one ends in a server error.",
   "steps": [
    "Send GET /users/refresh without an Authorization header.",
    "Send GET /users/refresh with Authorization \"Bearer not-a-jwt\"."
   ],
   "expected": "401 for both.",
   "actual": "500 with { \"message\": \"Server Error\" } for both.",
   "evidence": "GET /users/refresh (no Authorization), 2026-10-09 -> 500 {\"message\":\"Server Error\"}\nGET /users/refresh (Authorization: Bearer not-a-jwt), 2026-10-09 -> 500 {\"message\":\"Server Error\"}",
   "file": "bugs/BUG-006.yml",
   "yaml": "id: BUG-006\ntitle: Token refresh returns 500 instead of 401 without a token or with a malformed one\nstatus: open\nseverity: major\nlayer: api\narea: users\naffects:\n  - GET /users/refresh\nfound: 2026-10-03\nref:\n  - docs/api/contracts/Users_API.md#7-refresh-token\ndescription: >-\n  An expired or invalidated token gets a proper 401; only a missing or unparsable one ends in a server error.\nsteps:\n  - Send GET /users/refresh without an Authorization header.\n  - Send GET /users/refresh with Authorization \"Bearer not-a-jwt\".\nexpected: 401 for both.\nactual: '500 with { \"message\": \"Server Error\" } for both.'\nevidence: |-\n  GET /users/refresh (no Authorization), 2026-10-09 -> 500 {\"message\":\"Server Error\"}\n  GET /users/refresh (Authorization: Bearer not-a-jwt), 2026-10-09 -> 500 {\"message\":\"Server Error\"}",
   "scenarios": [
    {
     "id": "API-0112",
     "name": "Refresh without a token returns 401",
     "layer": "api",
     "area": "users",
     "file": "test-scenarios/api/users/get-users-refresh.yml",
     "status": "automated",
     "automatedIn": "tests/api/users/get-users-refresh.spec.ts",
     "specLine": 128,
     "knownIssue": "Returns 500 instead of 401 when the request has no token."
    },
    {
     "id": "API-0113",
     "name": "Refresh with a malformed token returns 401",
     "layer": "api",
     "area": "users",
     "file": "test-scenarios/api/users/get-users-refresh.yml",
     "status": "automated",
     "automatedIn": "tests/api/users/get-users-refresh.spec.ts",
     "specLine": 142,
     "knownIssue": "Returns 500 instead of 401 for a malformed token."
    }
   ]
  },
  {
   "id": "BUG-007",
   "title": "Registration accepts customers older than 75; the age limit only rejects birth dates more than 93 years ago",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "users",
   "affects": [
    "POST /users/register"
   ],
   "found": "2026-10-03",
   "ref": [
    "docs/api/contracts/Users_API.md#notes"
   ],
   "description": "The rule behind \"Customer must be younger than 75 years old.\" subtracts 75 years from a date that already had 18 subtracted (the minimum-age check), so the upper limit is 93 years, not 75.",
   "steps": [
    "Send POST /users/register with a unique email, a first name, a last name, a random strong password and a dob 80 years ago in YYYY-MM-DD."
   ],
   "expected": "422 with the dob message \"Customer must be younger than 75 years old.\".",
   "actual": "201; the customer is registered.",
   "file": "bugs/BUG-007.yml",
   "yaml": "id: BUG-007\ntitle: Registration accepts customers older than 75; the age limit only rejects birth dates more than 93 years ago\nstatus: open\nseverity: major\nlayer: api\narea: users\naffects:\n  - POST /users/register\nfound: 2026-10-03\nref:\n  - docs/api/contracts/Users_API.md#notes\ndescription: >-\n  The rule behind \"Customer must be younger than 75 years old.\" subtracts 75 years from a date that\n  already had 18 subtracted (the minimum-age check), so the upper limit is 93 years, not 75.\nsteps:\n  - Send POST /users/register with a unique email, a first name, a last name, a random strong password and a dob 80 years ago in YYYY-MM-DD.\nexpected: 422 with the dob message \"Customer must be younger than 75 years old.\".\nactual: 201; the customer is registered.",
   "scenarios": [
    {
     "id": "API-0099",
     "name": "Register a customer older than 75 returns 422",
     "layer": "api",
     "area": "users",
     "file": "test-scenarios/api/users/post-users-register.yml",
     "status": "automated",
     "automatedIn": "tests/api/users/post-users-register.spec.ts",
     "specLine": 421,
     "knownIssue": "Accepts a customer born 80 years ago (201) instead of 422; the 75-year age limit only rejects birth dates more than 93 years ago."
    }
   ]
  },
  {
   "id": "BUG-008",
   "title": "Cart quantity stops at 99 instead of the story's range of 1 to 999,999,999",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "carts",
   "affects": [
    "POST /carts/{cartId}",
    "/product/{productId}"
   ],
   "found": "2026-10-04",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC7",
    "docs/analysis/product-detail.md",
    "docs/api/contracts/Carts_API.md#2-add-item-to-cart"
   ],
   "description": "The story requires quantities from 1 to 999,999,999, but the app caps them at 99 in three places: the server's validation (max:99 in CartController::addItem), the browser's cart service and the product page's quantity field (MAX_QUANTITY = 99).",
   "steps": [
    "Send POST /carts with an empty body and take the returned id.",
    "Send POST /carts/{cartId} with that id, an existing product's id as product_id and quantity 999999999."
   ],
   "expected": "200, and GET /carts/{cartId} shows the item with quantity 999999999.",
   "actual": "422 with a quantity error; the server accepts at most 99.",
   "evidence": "Page inspector, /product/01M4H0KC65RV1AZDGBVVX7XJ9G (Combination Pliers, logged out), 2026-10-09\n-> data-test \"quantity\": input[number], limits: min 1, max 99\nSource (practice-software-testing, sprint5), 2026-10-09:\nUI detail.component.ts validateQuantity(): a typed value above MAX_QUANTITY (99) becomes 99,\n  with the toast \"You can order at most 99 of this product.\"\nUI cart.service.ts addItem()/replaceQuantity(): Math.min(Math.max(1, quantity), 99)\nAPI CartController addItem/updateQuantity: 'quantity' => 'required|integer|min:1|max:99'",
   "file": "bugs/BUG-008.yml",
   "yaml": "id: BUG-008\ntitle: Cart quantity stops at 99 instead of the story's range of 1 to 999,999,999\nstatus: open\nseverity: major\nlayer: api\narea: carts\naffects:\n  - POST /carts/{cartId}\n  - /product/{productId}\nfound: 2026-10-04\nref:\n  - docs/ui/user-stories/Product_Detail.md#AC7\n  - docs/analysis/product-detail.md\n  - docs/api/contracts/Carts_API.md#2-add-item-to-cart\ndescription: >-\n  The story requires quantities from 1 to 999,999,999, but the app caps them at 99 in three places:\n  the server's validation (max:99 in CartController::addItem), the browser's cart service and the\n  product page's quantity field (MAX_QUANTITY = 99).\nsteps:\n  - Send POST /carts with an empty body and take the returned id.\n  - Send POST /carts/{cartId} with that id, an existing product's id as product_id and quantity 999999999.\nexpected: 200, and GET /carts/{cartId} shows the item with quantity 999999999.\nactual: 422 with a quantity error; the server accepts at most 99.\nevidence: |-\n  Page inspector, /product/01M4H0KC65RV1AZDGBVVX7XJ9G (Combination Pliers, logged out), 2026-10-09\n  -> data-test \"quantity\": input[number], limits: min 1, max 99\n  Source (practice-software-testing, sprint5), 2026-10-09:\n  UI detail.component.ts validateQuantity(): a typed value above MAX_QUANTITY (99) becomes 99,\n    with the toast \"You can order at most 99 of this product.\"\n  UI cart.service.ts addItem()/replaceQuantity(): Math.min(Math.max(1, quantity), 99)\n  API CartController addItem/updateQuantity: 'quantity' => 'required|integer|min:1|max:99'",
   "scenarios": [
    {
     "id": "API-0118",
     "name": "Add a product with quantity 999,999,999 to a cart returns 200 and the cart holds it",
     "layer": "api",
     "area": "carts",
     "file": "test-scenarios/api/carts/post-carts-by-cart-id.yml",
     "status": "automated",
     "automatedIn": "tests/api/carts/post-carts-by-cart-id.spec.ts",
     "specLine": 235,
     "knownIssue": "Returns 422 for a quantity of 999,999,999 (the server allows at most 99) instead of adding it to the cart as the story's range 1 to 999,999,999 requires."
    },
    {
     "id": "UI-024",
     "name": "A typed quantity above 999,999,999 is set to 999,999,999",
     "layer": "ui",
     "area": "products",
     "file": "test-scenarios/ui/products/product-quantity.yml",
     "status": "manual",
     "knownIssue": "The field sets a typed quantity above 99 to 99 (with the warning \"You can order at most 99 of this product.\") instead of setting 1,000,000,000 to 999,999,999 as the story's range 1 to 999,999,999 requires."
    },
    {
     "id": "UI-025",
     "name": "A typed quantity of 999,999,999 is accepted",
     "layer": "ui",
     "area": "products",
     "file": "test-scenarios/ui/products/product-quantity.yml",
     "status": "manual",
     "knownIssue": "The field changes a typed quantity of 999,999,999 to 99 (the app allows at most 99) instead of keeping it as the story's range 1 to 999,999,999 requires."
    }
   ]
  },
  {
   "id": "BUG-011",
   "title": "Brand search returns 500 instead of 422 when q is sent as an array",
   "status": "open",
   "severity": "major",
   "layer": "api",
   "area": "brands",
   "affects": [
    "GET /brands/search",
    "QUERY /brands/search"
   ],
   "found": "2026-10-10",
   "ref": [
    "docs/api/contracts/Brands_API.md#7-search-brands",
    "docs/api/contracts/Brands_API.md#8-search-brands-http-query"
   ],
   "description": "q isn't validated: BrandService::searchBrands builds its cache key and log line from it, and an array fails the string conversion, which ends in a server error. GET and QUERY share the code path.",
   "steps": [
    "Send GET /brands/search with q as an array (q[]=x).",
    "Send QUERY /brands/search with Content-Type: application/json and the body { \"q\": [\"x\"] }."
   ],
   "expected": "422 naming q, or 200 with q treated as text.",
   "actual": "500 with { \"message\": \"Server Error\" } for GET (reproduced); QUERY from the source (same code path).",
   "evidence": "GET /brands/search?q[]=x (Accept: application/json), 2026-10-10 08:03 UTC\n-> 500 {\"message\":\"Server Error\"}\nGET /brands/search?q=forge, 2026-10-10 -> 200, 1 brand (control)\nSource (practice-software-testing, sprint5/API): BrandService::searchBrands: $cacheKey = \"brands.search.{$query}\"",
   "file": "bugs/BUG-011.yml",
   "yaml": "id: BUG-011\ntitle: Brand search returns 500 instead of 422 when q is sent as an array\nstatus: open\nseverity: major\nlayer: api\narea: brands\naffects:\n  - GET /brands/search\n  - QUERY /brands/search\nfound: 2026-10-10\nref:\n  - docs/api/contracts/Brands_API.md#7-search-brands\n  - docs/api/contracts/Brands_API.md#8-search-brands-http-query\ndescription: >-\n  q isn't validated: BrandService::searchBrands builds its cache key and log line from it, and an array\n  fails the string conversion, which ends in a server error. GET and QUERY share the code path.\nsteps:\n  - Send GET /brands/search with q as an array (q[]=x).\n  - 'Send QUERY /brands/search with Content-Type: application/json and the body { \"q\": [\"x\"] }.'\nexpected: 422 naming q, or 200 with q treated as text.\nactual: '500 with { \"message\": \"Server Error\" } for GET (reproduced); QUERY from the source (same code path).'\nevidence: |-\n  GET /brands/search?q[]=x (Accept: application/json), 2026-10-10 08:03 UTC\n  -> 500 {\"message\":\"Server Error\"}\n  GET /brands/search?q=forge, 2026-10-10 -> 200, 1 brand (control)\n  Source (practice-software-testing, sprint5/API): BrandService::searchBrands: $cacheKey = \"brands.search.{$query}\"",
   "scenarios": []
  },
  {
   "id": "BUG-005",
   "title": "Related products omit co2_rating, so is_eco_friendly is always false",
   "status": "open",
   "severity": "minor",
   "layer": "api",
   "area": "products",
   "affects": [
    "GET /products/{productId}/related"
   ],
   "found": "2026-10-02",
   "ref": [
    "docs/api/contracts/Products_API.md#notes"
   ],
   "description": "The related-products query doesn't select co2_rating, so the field is missing and is_eco_friendly, which is derived from it, is false for every related product. The same products from GET /products/{productId} have it.",
   "steps": [
    "Send GET /products and take the first item's id.",
    "Send GET /products/{productId}/related with that id.",
    "Compare the items with GET /products/{productId} for each of them."
   ],
   "expected": "Every related product has co2_rating, and is_eco_friendly matches it.",
   "actual": "No related product has co2_rating, and is_eco_friendly is false for all of them.",
   "evidence": "GET /products/01M4GX5NBG86XPB5G15W625EMS/related, 2026-10-09\n-> 200, 4 items with keys id, name, description, price, is_location_offer, is_rental, in_stock,\n   is_eco_friendly (false), product_image, category, brand; no co2_rating\nGET /products/01M4GX5NBG86XPB5G15W625EMS -> co2_rating \"D\"",
   "file": "bugs/BUG-005.yml",
   "yaml": "id: BUG-005\ntitle: Related products omit co2_rating, so is_eco_friendly is always false\nstatus: open\nseverity: minor\nlayer: api\narea: products\naffects:\n  - GET /products/{productId}/related\nfound: 2026-10-02\nref:\n  - docs/api/contracts/Products_API.md#notes\ndescription: >-\n  The related-products query doesn't select co2_rating, so the field is missing and is_eco_friendly,\n  which is derived from it, is false for every related product. The same products from GET /products/{productId} have it.\nsteps:\n  - Send GET /products and take the first item's id.\n  - Send GET /products/{productId}/related with that id.\n  - Compare the items with GET /products/{productId} for each of them.\nexpected: Every related product has co2_rating, and is_eco_friendly matches it.\nactual: No related product has co2_rating, and is_eco_friendly is false for all of them.\nevidence: |-\n  GET /products/01M4GX5NBG86XPB5G15W625EMS/related, 2026-10-09\n  -> 200, 4 items with keys id, name, description, price, is_location_offer, is_rental, in_stock,\n     is_eco_friendly (false), product_image, category, brand; no co2_rating\n  GET /products/01M4GX5NBG86XPB5G15W625EMS -> co2_rating \"D\"",
   "scenarios": [
    {
     "id": "API-0025",
     "name": "Related products include their CO2 rating",
     "layer": "api",
     "area": "products",
     "file": "test-scenarios/api/products/get-products-by-product-id-related.yml",
     "status": "automated",
     "automatedIn": "tests/api/products/get-products-by-product-id-related.spec.ts",
     "specLine": 87,
     "knownIssue": "Omits co2_rating from related products, so is_eco_friendly is always false."
    }
   ]
  },
  {
   "id": "BUG-010",
   "title": "Partial brand update returns 409 when the body repeats the brand's own slug, instead of 200",
   "status": "open",
   "severity": "minor",
   "layer": "api",
   "area": "brands",
   "affects": [
    "PATCH /brands/{brandId}"
   ],
   "found": "2026-10-10",
   "ref": [
    "docs/api/contracts/Brands_API.md#5-partially-update-brand",
    "docs/api/contracts/Brands_API.md#notes"
   ],
   "description": "The slug's uniqueness rule in PatchBrand doesn't ignore the brand being patched, so a client that sends every field (the current slug unchanged) can't update the name. Workaround: leave slug out of the body. PUT has no uniqueness rule and accepts the own slug.",
   "steps": [
    "Send POST /brands with a unique name and a unique slug, and take the new brand's id.",
    "Send PATCH /brands/{brandId} for that brand with a new name and the brand's own slug."
   ],
   "expected": "200 with { success true }, and the brand has the new name; a slug only conflicts with other brands' slugs.",
   "actual": "409 with { \"slug\": [\"A brand already exists with this slug.\"] }, and the name doesn't change.",
   "evidence": "Throwaway brand, 2026-10-10 08:07 UTC (deleted as admin afterwards, 204)\nPATCH /brands/{brandId} { name: new, slug: the brand's own slug }\n-> 409 {\"slug\":[\"A brand already exists with this slug.\"]}\nGET /brands/{brandId} -> 200, the previous name\nSource (practice-software-testing, sprint5/API): PatchBrand::rules():\n  'slug' => ['sometimes', 'alpha_dash:ascii', 'unique:brands,slug', ...] (no ignore of the current id)",
   "file": "bugs/BUG-010.yml",
   "yaml": "id: BUG-010\ntitle: Partial brand update returns 409 when the body repeats the brand's own slug, instead of 200\nstatus: open\nseverity: minor\nlayer: api\narea: brands\naffects:\n  - PATCH /brands/{brandId}\nfound: 2026-10-10\nref:\n  - docs/api/contracts/Brands_API.md#5-partially-update-brand\n  - docs/api/contracts/Brands_API.md#notes\ndescription: >-\n  The slug's uniqueness rule in PatchBrand doesn't ignore the brand being patched, so a client that sends\n  every field (the current slug unchanged) can't update the name. Workaround: leave slug out of the body.\n  PUT has no uniqueness rule and accepts the own slug.\nsteps:\n  - Send POST /brands with a unique name and a unique slug, and take the new brand's id.\n  - Send PATCH /brands/{brandId} for that brand with a new name and the brand's own slug.\nexpected: 200 with { success true }, and the brand has the new name; a slug only conflicts with other brands' slugs.\nactual: >-\n  409 with { \"slug\": [\"A brand already exists with this slug.\"] }, and the name doesn't change.\nevidence: |-\n  Throwaway brand, 2026-10-10 08:07 UTC (deleted as admin afterwards, 204)\n  PATCH /brands/{brandId} { name: new, slug: the brand's own slug }\n  -> 409 {\"slug\":[\"A brand already exists with this slug.\"]}\n  GET /brands/{brandId} -> 200, the previous name\n  Source (practice-software-testing, sprint5/API): PatchBrand::rules():\n    'slug' => ['sometimes', 'alpha_dash:ascii', 'unique:brands,slug', ...] (no ignore of the current id)",
   "scenarios": []
  },
  {
   "id": "BUG-013",
   "title": "Brand search keeps returning stale results for up to an hour after a brand is created, updated or deleted",
   "status": "open",
   "severity": "minor",
   "layer": "api",
   "area": "brands",
   "affects": [
    "GET /brands/search",
    "QUERY /brands/search"
   ],
   "found": "2026-10-10",
   "ref": [
    "docs/api/contracts/Brands_API.md#7-search-brands",
    "docs/api/contracts/Brands_API.md#notes"
   ],
   "description": "BrandService caches each search term for 1 hour, but create, update and delete clear only the list and the brand's own entry, never the search entries. A term searched before the change keeps its old result: a new or renamed brand is missing, a deleted one is still listed.",
   "steps": [
    "Send GET /brands/search with a unique term that no brand matches.",
    "Send POST /brands with that term as the name and a unique slug.",
    "Send GET /brands/search with the same term.",
    "Send DELETE /brands/{brandId} for the new brand as admin."
   ],
   "expected": "The search right after the POST returns the new brand, like GET /brands does.",
   "actual": "The search returns the cached empty list until the entry expires, up to an hour later (from the source, not reproduced).",
   "evidence": "Source (practice-software-testing, sprint5/API), 2026-10-10, BrandService:\nsearchBrands: Cache::remember(\"brands.search.{$query}\", 60 * 60, ...)\ncreate, update, delete: Cache::forget('brands.all') and Cache::forget(\"brands.{$id}\") only",
   "file": "bugs/BUG-013.yml",
   "yaml": "id: BUG-013\ntitle: Brand search keeps returning stale results for up to an hour after a brand is created, updated or deleted\nstatus: open\nseverity: minor\nlayer: api\narea: brands\naffects:\n  - GET /brands/search\n  - QUERY /brands/search\nfound: 2026-10-10\nref:\n  - docs/api/contracts/Brands_API.md#7-search-brands\n  - docs/api/contracts/Brands_API.md#notes\ndescription: >-\n  BrandService caches each search term for 1 hour, but create, update and delete clear only the list and\n  the brand's own entry, never the search entries. A term searched before the change keeps its old result:\n  a new or renamed brand is missing, a deleted one is still listed.\nsteps:\n  - Send GET /brands/search with a unique term that no brand matches.\n  - Send POST /brands with that term as the name and a unique slug.\n  - Send GET /brands/search with the same term.\n  - Send DELETE /brands/{brandId} for the new brand as admin.\nexpected: The search right after the POST returns the new brand, like GET /brands does.\nactual: >-\n  The search returns the cached empty list until the entry expires, up to an hour later (from the source,\n  not reproduced).\nevidence: |-\n  Source (practice-software-testing, sprint5/API), 2026-10-10, BrandService:\n  searchBrands: Cache::remember(\"brands.search.{$query}\", 60 * 60, ...)\n  create, update, delete: Cache::forget('brands.all') and Cache::forget(\"brands.{$id}\") only",
   "scenarios": []
  },
  {
   "id": "BUG-012",
   "title": "Brand update with a duplicate slug returns 409 with \"Duplicate Entry\" instead of the slug's validation message",
   "status": "open",
   "severity": "trivial",
   "layer": "api",
   "area": "brands",
   "affects": [
    "PUT /brands/{brandId}"
   ],
   "found": "2026-10-10",
   "ref": [
    "docs/api/contracts/Brands_API.md#4-update-brand",
    "docs/api/contracts/Brands_API.md#notes"
   ],
   "description": "UpdateBrand has no uniqueness rule for slug, so a duplicate reaches the database's unique index and the global handler answers with a generic message. The status is right; only the body differs from POST and PATCH (and from the OpenAPI spec), so a client can't tell which field is wrong.",
   "steps": [
    "Send POST /brands twice with unique names and unique slugs, and take both brands' ids and slugs.",
    "Send PUT /brands/{brandId} for the second brand with the first brand's slug."
   ],
   "expected": "409 with { \"slug\": [\"A brand already exists with this slug.\"] }, like POST and PATCH /brands.",
   "actual": "409 with { \"message\": \"Duplicate Entry\" } (from the source; observed by the contract writer's live calls on 2026-10-10, not reproduced here).",
   "evidence": "Source (practice-software-testing, sprint5/API), 2026-10-10:\nUpdateBrand::rules(): 'slug' => ['alpha_dash:ascii', 'string', 'max:120', ...] (no unique rule)\napp/Exceptions/Handler.php: a unique-index violation (SQLSTATE 23000) -> 409 { message: \"Duplicate Entry\" }\nContract writer's live calls, 2026-10-10 (Brands_API.md, Update brand): 409 {\"message\":\"Duplicate Entry\"}",
   "file": "bugs/BUG-012.yml",
   "yaml": "id: BUG-012\ntitle: Brand update with a duplicate slug returns 409 with \"Duplicate Entry\" instead of the slug's validation message\nstatus: open\nseverity: trivial\nlayer: api\narea: brands\naffects:\n  - PUT /brands/{brandId}\nfound: 2026-10-10\nref:\n  - docs/api/contracts/Brands_API.md#4-update-brand\n  - docs/api/contracts/Brands_API.md#notes\ndescription: >-\n  UpdateBrand has no uniqueness rule for slug, so a duplicate reaches the database's unique index and the\n  global handler answers with a generic message. The status is right; only the body differs from POST and\n  PATCH (and from the OpenAPI spec), so a client can't tell which field is wrong.\nsteps:\n  - Send POST /brands twice with unique names and unique slugs, and take both brands' ids and slugs.\n  - Send PUT /brands/{brandId} for the second brand with the first brand's slug.\nexpected: '409 with { \"slug\": [\"A brand already exists with this slug.\"] }, like POST and PATCH /brands.'\nactual: >-\n  409 with { \"message\": \"Duplicate Entry\" } (from the source; observed by the contract writer's live\n  calls on 2026-10-10, not reproduced here).\nevidence: |-\n  Source (practice-software-testing, sprint5/API), 2026-10-10:\n  UpdateBrand::rules(): 'slug' => ['alpha_dash:ascii', 'string', 'max:120', ...] (no unique rule)\n  app/Exceptions/Handler.php: a unique-index violation (SQLSTATE 23000) -> 409 { message: \"Duplicate Entry\" }\n  Contract writer's live calls, 2026-10-10 (Brands_API.md, Update brand): 409 {\"message\":\"Duplicate Entry\"}",
   "scenarios": []
  }
 ]
};
