// Generated by scripts/build-test-cases.mts; do not edit.
window.SCENARIO_CATALOG = {
 "layer": "ui",
 "title": "UI Test Cases",
 "prefix": "UI",
 "generatedAt": "2026-10-08T17:48:20.890Z",
 "commit": "9eb7509654cee92b41d8af6d6f7d30ffcc6be561",
 "repoUrl": "https://github.com/Zaytsman/SimpRight",
 "branch": "main",
 "workflowUrl": "https://github.com/Zaytsman/SimpRight/actions/workflows/custom-ui-tests.yml",
 "stats": {
  "total": 30,
  "automated": 19,
  "manual": 11,
  "knownIssues": 0,
  "automatedPct": 63
 },
 "tree": [
  {
   "area": "cart",
   "label": "Cart",
   "files": [
    {
     "file": "test-scenarios/ui/cart/add-to-cart.yml",
     "name": "add-to-cart",
     "label": "Add to cart",
     "suite": "Cart",
     "tags": [
      "@cart"
     ],
     "ids": [
      "UI-002",
      "UI-027"
     ]
    }
   ]
  },
  {
   "area": "products",
   "label": "Products",
   "files": [
    {
     "file": "test-scenarios/ui/products/product-detail.yml",
     "name": "product-detail",
     "label": "Product detail",
     "suite": "Product detail",
     "tags": [
      "@products"
     ],
     "ids": [
      "UI-013",
      "UI-014",
      "UI-015",
      "UI-016",
      "UI-017"
     ]
    },
    {
     "file": "test-scenarios/ui/products/product-favorites.yml",
     "name": "product-favorites",
     "label": "Product favorites",
     "suite": "Product favourites",
     "tags": [
      "@products"
     ],
     "ids": [
      "UI-028",
      "UI-029",
      "UI-030"
     ]
    },
    {
     "file": "test-scenarios/ui/products/product-grid.yml",
     "name": "product-grid",
     "label": "Product grid",
     "suite": "Product grid",
     "tags": [
      "@products"
     ],
     "ids": [
      "UI-012"
     ]
    },
    {
     "file": "test-scenarios/ui/products/product-quantity.yml",
     "name": "product-quantity",
     "label": "Product quantity",
     "suite": "Product quantity",
     "tags": [
      "@products"
     ],
     "ids": [
      "UI-018",
      "UI-019",
      "UI-020",
      "UI-021",
      "UI-022",
      "UI-023",
      "UI-024",
      "UI-025",
      "UI-026"
     ]
    },
    {
     "file": "test-scenarios/ui/products/product-search.yml",
     "name": "product-search",
     "label": "Product search",
     "suite": "Product search",
     "tags": [
      "@products"
     ],
     "ids": [
      "UI-001",
      "UI-003",
      "UI-004",
      "UI-005",
      "UI-006",
      "UI-007"
     ]
    },
    {
     "file": "test-scenarios/ui/products/product-sorting.yml",
     "name": "product-sorting",
     "label": "Product sorting",
     "suite": "Product sorting",
     "tags": [
      "@products"
     ],
     "ids": [
      "UI-008",
      "UI-009",
      "UI-010",
      "UI-011"
     ]
    }
   ]
  }
 ],
 "scenarios": [
  {
   "id": "UI-002",
   "name": "Add a product with quantity 2 to the cart",
   "status": "automated",
   "automatedIn": "tests/ui/cart/add-to-cart.spec.ts",
   "steps": [
    "Create a product for this test through the API: a unique name, in stock.",
    "Search for that product and open it.",
    "Set the quantity to 2 and click \"Add to cart\".",
    "Verify the cart badge in the nav bar shows 2.",
    "Open the cart.",
    "Verify the cart has exactly one line: that product with quantity 2.",
    "Verify the cart total equals 2 × the product's unit price."
   ],
   "ref": [],
   "specLine": 6,
   "area": "cart",
   "areaLabel": "Cart",
   "file": "test-scenarios/ui/cart/add-to-cart.yml",
   "fileLabel": "Add to cart",
   "suite": "Cart",
   "tags": [
    "@cart"
   ],
   "yaml": "- id: UI-002\n  name: Add a product with quantity 2 to the cart\n  status: automated\n  automatedIn: tests/ui/cart/add-to-cart.spec.ts\n  steps:\n    - 'Create a product for this test through the API: a unique name, in stock.'\n    - Search for that product and open it.\n    - Set the quantity to 2 and click \"Add to cart\".\n    - Verify the cart badge in the nav bar shows 2.\n    - Open the cart.\n    - 'Verify the cart has exactly one line: that product with quantity 2.'\n    - Verify the cart total equals 2 × the product's unit price."
  },
  {
   "id": "UI-027",
   "name": "Adding a product to the cart shows a success message",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC8"
   ],
   "status": "manual",
   "steps": [
    "The cart is empty.",
    "Open the product \"Combination Pliers\".",
    "Click \"Add to cart\".",
    "Verify the message \"Product added to shopping cart.\" is shown."
   ],
   "area": "cart",
   "areaLabel": "Cart",
   "file": "test-scenarios/ui/cart/add-to-cart.yml",
   "fileLabel": "Add to cart",
   "suite": "Cart",
   "tags": [
    "@cart"
   ],
   "yaml": "- id: UI-027\n  name: Adding a product to the cart shows a success message\n  ref: docs/ui/user-stories/Product_Detail.md#AC8\n  status: manual\n  steps:\n    - The cart is empty.\n    - Open the product \"Combination Pliers\".\n    - Click \"Add to cart\".\n    - Verify the message \"Product added to shopping cart.\" is shown."
  },
  {
   "id": "UI-013",
   "name": "The product page shows the product's information and related products",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC1",
    "docs/ui/user-stories/Product_Detail.md#AC14"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-detail.spec.ts",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Verify the product image is shown.",
    "Verify the name \"Combination Pliers\" is shown.",
    "Verify the product description is shown.",
    "Verify the price \"$14.15\" is shown.",
    "Verify the category badge \"Pliers\" is shown.",
    "Verify the brand badge \"ForgeFlex Tools\" is shown.",
    "Verify the \"Related products\" section is shown below the product information.",
    "Verify the \"Related products\" section shows at least one product."
   ],
   "specLine": 6,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-detail.yml",
   "fileLabel": "Product detail",
   "suite": "Product detail",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-013\n  name: The product page shows the product's information and related products\n  ref:\n    - docs/ui/user-stories/Product_Detail.md#AC1\n    - docs/ui/user-stories/Product_Detail.md#AC14\n  status: automated\n  automatedIn: tests/ui/products/product-detail.spec.ts\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Verify the product image is shown.\n    - Verify the name \"Combination Pliers\" is shown.\n    - Verify the product description is shown.\n    - Verify the price \"$14.15\" is shown.\n    - Verify the category badge \"Pliers\" is shown.\n    - Verify the brand badge \"ForgeFlex Tools\" is shown.\n    - Verify the \"Related products\" section is shown below the product information.\n    - Verify the \"Related products\" section shows at least one product."
  },
  {
   "id": "UI-014",
   "name": "A discounted product shows the original price struck through, the discounted price and the discount badge",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC2"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-detail.spec.ts",
   "steps": [
    "Open a product that has a discount.",
    "Verify the original price is shown struck through.",
    "Verify the discounted price is shown.",
    "Verify a discount percentage badge is shown."
   ],
   "specLine": 58,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-detail.yml",
   "fileLabel": "Product detail",
   "suite": "Product detail",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-014\n  name: A discounted product shows the original price struck through, the discounted price and the discount badge\n  ref: docs/ui/user-stories/Product_Detail.md#AC2\n  status: automated\n  automatedIn: tests/ui/products/product-detail.spec.ts\n  steps:\n    - Open a product that has a discount.\n    - Verify the original price is shown struck through.\n    - Verify the discounted price is shown.\n    - Verify a discount percentage badge is shown."
  },
  {
   "id": "UI-015",
   "name": "An out-of-stock product can't be added to the cart",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC9"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-detail.spec.ts",
   "steps": [
    "Open the product \"Long Nose Pliers\".",
    "Verify \"Add to cart\" is disabled.",
    "Verify \"Out of stock\" is shown.",
    "Verify \"Out of stock\" is shown in red."
   ],
   "specLine": 86,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-detail.yml",
   "fileLabel": "Product detail",
   "suite": "Product detail",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-015\n  name: An out-of-stock product can't be added to the cart\n  ref: docs/ui/user-stories/Product_Detail.md#AC9\n  status: automated\n  automatedIn: tests/ui/products/product-detail.spec.ts\n  steps:\n    - Open the product \"Long Nose Pliers\".\n    - Verify \"Add to cart\" is disabled.\n    - Verify \"Out of stock\" is shown.\n    - Verify \"Out of stock\" is shown in red."
  },
  {
   "id": "UI-016",
   "name": "A rental product shows a duration slider instead of the quantity buttons",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC10"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-detail.spec.ts",
   "steps": [
    "Open the rental product \"Excavator\".",
    "Verify a duration slider is shown.",
    "Verify the duration slider goes from 1 to 10 hours.",
    "Verify the \"Increase quantity\" (+) and \"Decrease quantity\" (-) buttons are not shown."
   ],
   "specLine": 105,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-detail.yml",
   "fileLabel": "Product detail",
   "suite": "Product detail",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-016\n  name: A rental product shows a duration slider instead of the quantity buttons\n  ref: docs/ui/user-stories/Product_Detail.md#AC10\n  status: automated\n  automatedIn: tests/ui/products/product-detail.spec.ts\n  steps:\n    - Open the rental product \"Excavator\".\n    - Verify a duration slider is shown.\n    - Verify the duration slider goes from 1 to 10 hours.\n    - Verify the \"Increase quantity\" (+) and \"Decrease quantity\" (-) buttons are not shown."
  },
  {
   "id": "UI-017",
   "name": "A rental's total price is the hourly rate times the duration",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC10"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-detail.spec.ts",
   "steps": [
    "Open the rental product \"Excavator\".",
    "Set the duration slider to 3 hours.",
    "Verify the total price equals 3 × the hourly rate."
   ],
   "specLine": 127,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-detail.yml",
   "fileLabel": "Product detail",
   "suite": "Product detail",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-017\n  name: A rental's total price is the hourly rate times the duration\n  ref: docs/ui/user-stories/Product_Detail.md#AC10\n  status: automated\n  automatedIn: tests/ui/products/product-detail.spec.ts\n  steps:\n    - Open the rental product \"Excavator\".\n    - Set the duration slider to 3 hours.\n    - Verify the total price equals 3 × the hourly rate."
  },
  {
   "id": "UI-028",
   "name": "Adding a product to favourites shows a success message",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC11"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-favorites.spec.ts",
   "steps": [
    "The product \"Combination Pliers\" is not in the user's favourites.",
    "Open the product \"Combination Pliers\".",
    "Click \"Add to favourites\".",
    "Verify the message \"Product added to your favorites list.\" is shown."
   ],
   "specLine": 12,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-favorites.yml",
   "fileLabel": "Product favorites",
   "suite": "Product favourites",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-028\n  name: Adding a product to favourites shows a success message\n  ref: docs/ui/user-stories/Product_Detail.md#AC11\n  status: automated\n  automatedIn: tests/ui/products/product-favorites.spec.ts\n  steps:\n    - The product \"Combination Pliers\" is not in the user's favourites.\n    - Open the product \"Combination Pliers\".\n    - Click \"Add to favourites\".\n    - Verify the message \"Product added to your favorites list.\" is shown."
  },
  {
   "id": "UI-029",
   "name": "Adding a product that is already a favourite shows a message",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC12"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-favorites.spec.ts",
   "steps": [
    "The product \"Combination Pliers\" is in the user's favourites.",
    "Open the product \"Combination Pliers\".",
    "Click \"Add to favourites\".",
    "Verify the message \"Product already in your favorites list.\" is shown."
   ],
   "specLine": 34,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-favorites.yml",
   "fileLabel": "Product favorites",
   "suite": "Product favourites",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-029\n  name: Adding a product that is already a favourite shows a message\n  ref: docs/ui/user-stories/Product_Detail.md#AC12\n  status: automated\n  automatedIn: tests/ui/products/product-favorites.spec.ts\n  steps:\n    - The product \"Combination Pliers\" is in the user's favourites.\n    - Open the product \"Combination Pliers\".\n    - Click \"Add to favourites\".\n    - Verify the message \"Product already in your favorites list.\" is shown."
  },
  {
   "id": "UI-030",
   "name": "A logged-out visitor can't add a product to favourites",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC13"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-favorites.spec.ts",
   "role": "guest",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Click \"Add to favourites\".",
    "Verify the message \"Unauthorized, can not add product to your favorite list.\" is shown."
   ],
   "specLine": 67,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-favorites.yml",
   "fileLabel": "Product favorites",
   "suite": "Product favourites",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-030\n  name: A logged-out visitor can't add a product to favourites\n  ref: docs/ui/user-stories/Product_Detail.md#AC13\n  status: automated\n  automatedIn: tests/ui/products/product-favorites.spec.ts\n  role: guest\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Click \"Add to favourites\".\n    - Verify the message \"Unauthorized, can not add product to your favorite list.\" is shown."
  },
  {
   "id": "UI-012",
   "name": "An out-of-stock product shows \"Out of stock\" on its card",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC13"
   ],
   "status": "manual",
   "steps": [
    "Open the home page.",
    "Verify the card of \"Long Nose Pliers\" shows \"Out of stock\"."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-grid.yml",
   "fileLabel": "Product grid",
   "suite": "Product grid",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-012\n  name: An out-of-stock product shows \"Out of stock\" on its card\n  ref: docs/ui/user-stories/Product_Overview.md#AC13\n  status: manual\n  steps:\n    - Open the home page.\n    - Verify the card of \"Long Nose Pliers\" shows \"Out of stock\"."
  },
  {
   "id": "UI-018",
   "name": "An in-stock product shows the quantity selector set to 1",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC3"
   ],
   "status": "manual",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Verify the quantity field is shown.",
    "Verify the \"Increase quantity\" (+) button is shown.",
    "Verify the \"Decrease quantity\" (-) button is shown.",
    "Verify the quantity is 1."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-quantity.yml",
   "fileLabel": "Product quantity",
   "suite": "Product quantity",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-018\n  name: An in-stock product shows the quantity selector set to 1\n  ref: docs/ui/user-stories/Product_Detail.md#AC3\n  status: manual\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Verify the quantity field is shown.\n    - Verify the \"Increase quantity\" (+) button is shown.\n    - Verify the \"Decrease quantity\" (-) button is shown.\n    - Verify the quantity is 1."
  },
  {
   "id": "UI-019",
   "name": "The plus button increases the quantity by 1",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC4"
   ],
   "status": "manual",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Click \"Increase quantity\".",
    "Verify the quantity is 2."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-quantity.yml",
   "fileLabel": "Product quantity",
   "suite": "Product quantity",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-019\n  name: The plus button increases the quantity by 1\n  ref: docs/ui/user-stories/Product_Detail.md#AC4\n  status: manual\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Click \"Increase quantity\".\n    - Verify the quantity is 2."
  },
  {
   "id": "UI-020",
   "name": "The minus button decreases the quantity by 1",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC5"
   ],
   "status": "manual",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Click \"Increase quantity\".",
    "Click \"Increase quantity\".",
    "Verify the quantity is 3.",
    "Click \"Decrease quantity\".",
    "Verify the quantity is 2."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-quantity.yml",
   "fileLabel": "Product quantity",
   "suite": "Product quantity",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-020\n  name: The minus button decreases the quantity by 1\n  ref: docs/ui/user-stories/Product_Detail.md#AC5\n  status: manual\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Click \"Increase quantity\".\n    - Click \"Increase quantity\".\n    - Verify the quantity is 3.\n    - Click \"Decrease quantity\".\n    - Verify the quantity is 2."
  },
  {
   "id": "UI-021",
   "name": "The minus button keeps the quantity at 1",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC6"
   ],
   "status": "manual",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Verify the quantity is 1.",
    "Click \"Decrease quantity\".",
    "Verify the quantity is still 1."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-quantity.yml",
   "fileLabel": "Product quantity",
   "suite": "Product quantity",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-021\n  name: The minus button keeps the quantity at 1\n  ref: docs/ui/user-stories/Product_Detail.md#AC6\n  status: manual\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Verify the quantity is 1.\n    - Click \"Decrease quantity\".\n    - Verify the quantity is still 1."
  },
  {
   "id": "UI-022",
   "name": "A quantity typed into the field is used",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC7"
   ],
   "status": "manual",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Enter 5 in the quantity field.",
    "Verify the quantity is 5."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-quantity.yml",
   "fileLabel": "Product quantity",
   "suite": "Product quantity",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-022\n  name: A quantity typed into the field is used\n  ref: docs/ui/user-stories/Product_Detail.md#AC7\n  status: manual\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Enter 5 in the quantity field.\n    - Verify the quantity is 5."
  },
  {
   "id": "UI-023",
   "name": "A typed quantity of 0 is set to 1",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC7"
   ],
   "status": "manual",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Enter 0 in the quantity field.",
    "Verify the quantity is 1."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-quantity.yml",
   "fileLabel": "Product quantity",
   "suite": "Product quantity",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-023\n  name: A typed quantity of 0 is set to 1\n  ref: docs/ui/user-stories/Product_Detail.md#AC7\n  status: manual\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Enter 0 in the quantity field.\n    - Verify the quantity is 1."
  },
  {
   "id": "UI-024",
   "name": "A typed quantity above 999,999,999 is set to 999,999,999",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC7"
   ],
   "status": "manual",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Enter 1000000000 in the quantity field.",
    "Verify the quantity is 999999999."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-quantity.yml",
   "fileLabel": "Product quantity",
   "suite": "Product quantity",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-024\n  name: A typed quantity above 999,999,999 is set to 999,999,999\n  ref: docs/ui/user-stories/Product_Detail.md#AC7\n  status: manual\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Enter 1000000000 in the quantity field.\n    - Verify the quantity is 999999999."
  },
  {
   "id": "UI-025",
   "name": "A typed quantity of 999,999,999 is accepted",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC7"
   ],
   "status": "manual",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Enter 999999999 in the quantity field.",
    "Verify the quantity is 999999999."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-quantity.yml",
   "fileLabel": "Product quantity",
   "suite": "Product quantity",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-025\n  name: A typed quantity of 999,999,999 is accepted\n  ref: docs/ui/user-stories/Product_Detail.md#AC7\n  status: manual\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Enter 999999999 in the quantity field.\n    - Verify the quantity is 999999999."
  },
  {
   "id": "UI-026",
   "name": "A typed quantity of 1 is accepted",
   "ref": [
    "docs/ui/user-stories/Product_Detail.md#AC7"
   ],
   "status": "manual",
   "steps": [
    "Open the product \"Combination Pliers\".",
    "Click \"Increase quantity\".",
    "Enter 1 in the quantity field.",
    "Verify the quantity is 1."
   ],
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-quantity.yml",
   "fileLabel": "Product quantity",
   "suite": "Product quantity",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-026\n  name: A typed quantity of 1 is accepted\n  ref: docs/ui/user-stories/Product_Detail.md#AC7\n  status: manual\n  steps:\n    - Open the product \"Combination Pliers\".\n    - Click \"Increase quantity\".\n    - Enter 1 in the quantity field.\n    - Verify the quantity is 1."
  },
  {
   "id": "UI-001",
   "name": "Search by name shows only matching products",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC4"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-search.spec.ts",
   "steps": [
    "Open the home page.",
    "Search for \"pliers\".",
    "Verify the caption reads \"Searched for: pliers\".",
    "Verify at least one product is shown.",
    "Verify every product name contains \"pliers\" (case-insensitive)."
   ],
   "specLine": 6,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-search.yml",
   "fileLabel": "Product search",
   "suite": "Product search",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-001\n  name: Search by name shows only matching products\n  ref: docs/ui/user-stories/Product_Overview.md#AC4\n  status: automated\n  automatedIn: tests/ui/products/product-search.spec.ts\n  steps:\n    - Open the home page.\n    - Search for \"pliers\".\n    - 'Verify the caption reads \"Searched for: pliers\".'\n    - Verify at least one product is shown.\n    - Verify every product name contains \"pliers\" (case-insensitive)."
  },
  {
   "id": "UI-003",
   "name": "Search resets the active category and brand filters",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC4"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-search.spec.ts",
   "steps": [
    "Open the home page.",
    "Check the category \"Hammer\" in the sidebar.",
    "Check the brand \"ForgeFlex Tools\" in the sidebar.",
    "Search for \"pliers\".",
    "Verify the category \"Hammer\" is not checked.",
    "Verify the brand \"ForgeFlex Tools\" is not checked.",
    "Verify at least one product is shown.",
    "Verify every product name contains \"pliers\" (case-insensitive)."
   ],
   "specLine": 33,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-search.yml",
   "fileLabel": "Product search",
   "suite": "Product search",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-003\n  name: Search resets the active category and brand filters\n  ref: docs/ui/user-stories/Product_Overview.md#AC4\n  status: automated\n  automatedIn: tests/ui/products/product-search.spec.ts\n  steps:\n    - Open the home page.\n    - Check the category \"Hammer\" in the sidebar.\n    - Check the brand \"ForgeFlex Tools\" in the sidebar.\n    - Search for \"pliers\".\n    - Verify the category \"Hammer\" is not checked.\n    - Verify the brand \"ForgeFlex Tools\" is not checked.\n    - Verify at least one product is shown.\n    - Verify every product name contains \"pliers\" (case-insensitive)."
  },
  {
   "id": "UI-004",
   "name": "Search with a 3-character term is accepted",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC4"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-search.spec.ts",
   "steps": [
    "Open the home page.",
    "Search for \"ham\".",
    "Verify the caption reads \"Searched for: ham\".",
    "Verify at least one product is shown.",
    "Verify every product name contains \"ham\" (case-insensitive)."
   ],
   "specLine": 74,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-search.yml",
   "fileLabel": "Product search",
   "suite": "Product search",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-004\n  name: Search with a 3-character term is accepted\n  ref: docs/ui/user-stories/Product_Overview.md#AC4\n  status: automated\n  automatedIn: tests/ui/products/product-search.spec.ts\n  steps:\n    - Open the home page.\n    - Search for \"ham\".\n    - 'Verify the caption reads \"Searched for: ham\".'\n    - Verify at least one product is shown.\n    - Verify every product name contains \"ham\" (case-insensitive)."
  },
  {
   "id": "UI-005",
   "name": "Search with a 40-character term is accepted",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC4"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-search.spec.ts",
   "steps": [
    "Open the home page.",
    "Search for a term of exactly 40 characters.",
    "Verify the caption reads \"Searched for: \" followed by the term."
   ],
   "specLine": 101,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-search.yml",
   "fileLabel": "Product search",
   "suite": "Product search",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-005\n  name: Search with a 40-character term is accepted\n  ref: docs/ui/user-stories/Product_Overview.md#AC4\n  status: automated\n  automatedIn: tests/ui/products/product-search.spec.ts\n  steps:\n    - Open the home page.\n    - Search for a term of exactly 40 characters.\n    - 'Verify the caption reads \"Searched for: \" followed by the term.'"
  },
  {
   "id": "UI-006",
   "name": "Search with a 2-character term is rejected",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC4"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-search.spec.ts",
   "steps": [
    "Open the home page.",
    "Search for \"pl\".",
    "Verify no \"Searched for:\" caption is shown.",
    "Verify the product grid still shows the first page of all products."
   ],
   "specLine": 117,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-search.yml",
   "fileLabel": "Product search",
   "suite": "Product search",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-006\n  name: Search with a 2-character term is rejected\n  ref: docs/ui/user-stories/Product_Overview.md#AC4\n  status: automated\n  automatedIn: tests/ui/products/product-search.spec.ts\n  steps:\n    - Open the home page.\n    - Search for \"pl\".\n    - 'Verify no \"Searched for:\" caption is shown.'\n    - Verify the product grid still shows the first page of all products."
  },
  {
   "id": "UI-007",
   "name": "Search with a 41-character term is rejected",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC4"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-search.spec.ts",
   "steps": [
    "Open the home page.",
    "Search for a term of exactly 41 characters.",
    "Verify no \"Searched for:\" caption is shown.",
    "Verify the product grid still shows the first page of all products."
   ],
   "specLine": 143,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-search.yml",
   "fileLabel": "Product search",
   "suite": "Product search",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-007\n  name: Search with a 41-character term is rejected\n  ref: docs/ui/user-stories/Product_Overview.md#AC4\n  status: automated\n  automatedIn: tests/ui/products/product-search.spec.ts\n  steps:\n    - Open the home page.\n    - Search for a term of exactly 41 characters.\n    - 'Verify no \"Searched for:\" caption is shown.'\n    - Verify the product grid still shows the first page of all products."
  },
  {
   "id": "UI-008",
   "name": "Sort by name from A to Z",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC9"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-sorting.spec.ts",
   "steps": [
    "Open the home page.",
    "Select \"Name (A - Z)\" in the sort list.",
    "Verify the product names are in alphabetical order, A to Z."
   ],
   "specLine": 9,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-sorting.yml",
   "fileLabel": "Product sorting",
   "suite": "Product sorting",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-008\n  name: Sort by name from A to Z\n  ref: docs/ui/user-stories/Product_Overview.md#AC9\n  status: automated\n  automatedIn: tests/ui/products/product-sorting.spec.ts\n  steps:\n    - Open the home page.\n    - Select \"Name (A - Z)\" in the sort list.\n    - Verify the product names are in alphabetical order, A to Z."
  },
  {
   "id": "UI-009",
   "name": "Sort by name from Z to A",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC9"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-sorting.spec.ts",
   "steps": [
    "Open the home page.",
    "Select \"Name (Z - A)\" in the sort list.",
    "Verify the product names are in reverse alphabetical order, Z to A."
   ],
   "specLine": 25,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-sorting.yml",
   "fileLabel": "Product sorting",
   "suite": "Product sorting",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-009\n  name: Sort by name from Z to A\n  ref: docs/ui/user-stories/Product_Overview.md#AC9\n  status: automated\n  automatedIn: tests/ui/products/product-sorting.spec.ts\n  steps:\n    - Open the home page.\n    - Select \"Name (Z - A)\" in the sort list.\n    - Verify the product names are in reverse alphabetical order, Z to A."
  },
  {
   "id": "UI-010",
   "name": "Sort by price from high to low",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC9"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-sorting.spec.ts",
   "steps": [
    "Open the home page.",
    "Select \"Price (High - Low)\" in the sort list.",
    "Verify the products are sorted by price, highest first."
   ],
   "specLine": 41,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-sorting.yml",
   "fileLabel": "Product sorting",
   "suite": "Product sorting",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-010\n  name: Sort by price from high to low\n  ref: docs/ui/user-stories/Product_Overview.md#AC9\n  status: automated\n  automatedIn: tests/ui/products/product-sorting.spec.ts\n  steps:\n    - Open the home page.\n    - Select \"Price (High - Low)\" in the sort list.\n    - Verify the products are sorted by price, highest first."
  },
  {
   "id": "UI-011",
   "name": "Sort by price from low to high",
   "ref": [
    "docs/ui/user-stories/Product_Overview.md#AC9"
   ],
   "status": "automated",
   "automatedIn": "tests/ui/products/product-sorting.spec.ts",
   "steps": [
    "Open the home page.",
    "Select \"Price (Low - High)\" in the sort list.",
    "Verify the products are sorted by price, lowest first."
   ],
   "specLine": 57,
   "area": "products",
   "areaLabel": "Products",
   "file": "test-scenarios/ui/products/product-sorting.yml",
   "fileLabel": "Product sorting",
   "suite": "Product sorting",
   "tags": [
    "@products"
   ],
   "yaml": "- id: UI-011\n  name: Sort by price from low to high\n  ref: docs/ui/user-stories/Product_Overview.md#AC9\n  status: automated\n  automatedIn: tests/ui/products/product-sorting.spec.ts\n  steps:\n    - Open the home page.\n    - Select \"Price (Low - High)\" in the sort list.\n    - Verify the products are sorted by price, lowest first."
  }
 ]
};
